name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate GitHub Contribution Snake
    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: noufbamne
          outputs: |
            dist/github-contribution-grid-snake.svg

          # Custom pink theme
          color_snake: '#FF69B4'
          color_dots: '#FFC0CB,#FFB6C1,#FF69B4,#DB7093,#C71585'

      - name: Push snake animation to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
